In [2]:
import pandas as pd


In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [7]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


In [8]:
import numpy as np

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [17]:
a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [22]:
a[2]=10

In [24]:
a

array([ 1,  2, 10,  4,  5,  6,  7])

In [30]:
np.arange(6,11)

array([ 6,  7,  8,  9, 10])

In [40]:
np.linspace(0,20,7) #gives 7 random numbers from 0 to 20 

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

Multi dimentional Array

In [41]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
b = np.array([[1,2,3], [4,4,2], [8,10,2]])

In [54]:
 b[:, 1]

array([ 2,  4, 10])

In [55]:
b[:]

array([[ 1,  2,  3],
       [ 4,  4,  2],
       [ 8, 10,  2]])

In [57]:
b

array([[ 1,  2,  3],
       [ 4,  4,  2],
       [ 8, 10,  2]])

Random generated Array

In [67]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [68]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element wise operations

In [79]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [80]:
b  = a /2

In [85]:
c = a + b
c

array([0. , 1.5, 3. , 4.5, 6. ])

Comparison operations

In [86]:
a

array([0, 1, 2, 3, 4])

In [89]:
a>=c

array([ True, False, False, False, False])

In [94]:
a = np.random.randint(low=2, high=20, size=(1,20))

In [95]:
a

array([[16, 14,  6, 17, 19,  9, 16, 10, 15, 17, 11, 15, 10, 19, 11, 11,
        16,  2, 13,  2]])

In [96]:
b = np.random.randint(low=0, high=30, size=(1,20))

In [97]:
b

array([[26, 18,  8, 12, 10,  8,  2, 28,  9, 22,  5,  6, 22,  6, 19, 24,
        18,  1,  4,  8]])

In [109]:
result = a<b

In [115]:
result = (result[0])

In [118]:
result.astype(int)

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1])

summarization operations

In [120]:
b.max()

np.int64(28)

In [123]:
b.min() < a.min()

np.True_